<?php
echo "Places";
?>




<div class="hero-unit filler" style="margin-top: 45px;">
	<div class="row">
		<form class="form-horizontal">
			<div class="span3">
				<p style="text-decoration: underline;">Add Places</p>
				<a href="#" class="btn primary"> <img
					src="https://geoloqi.com/geoloqi-core/assets/img/logo-block.544404.png" />
				</a>

				<div>
					<p class="help-block">Distance buffer of 5 miles gets applied
						(slider to come)</p>
				</div>
				
				<p style="text-decoration: underline; margin-top:6px;">Manage My Locations</p>
				<div style="margin-left:-28px">
				<div><div style="display: inline;" id="surfaceElement1" style="margin-top:5px;"></div><span style="display: inline;">remove</span></div>
				<div><div style="display: inline;" id="surfaceElement2" style="margin-top:5px;"></div><span style="display: inline;">remove</span></div>
				<div><div style="display: inline;" id="surfaceElement3" style="margin-top:5px;"></div><span style="display: inline;">remove</span></div>
				</div>
				<div>
					<p class="help-block">Store up to three notification areas (for free!)</p>
				</div>


			</div>
			<div class="span7">
				<div id="map" style="width: 100%; height: 100%;"></div>
			</div>
		</form>
	</div>
</div>