<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Foursquare | Hackathon!!'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js') ?>
                                  
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=7, IE=9" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <title>Get Current Location</title>
    <link href='http://serverapi.arcgisonline.com/jsapi/arcgis/3.2/js/dojo/dojox/mobile/themes/iPhone/iPhone.css' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="http://serverapi.arcgisonline.com/jsapi/arcgis/3.2/js/esri/css/esri.css" />
 
     <style>
          html, body { height: 100%; width: 100%; margin: 0; padding: 0; }
    </style>
    <script type="text/javascript">
      var dojoConfig = {
        parseOnLoad: true
      };
    </script>
    <script type="text/javascript" src="http://serverapi.arcgisonline.com/jsapi/arcgis/?v=3.2compact">
    </script>
    
    
    <script language="JavaScript" type="text/javascript">
      dojo.require("esri.map");
      dojo.requireIf(!dojo.isWebKit, "dojox.mobile.compat");
      dojo.require("esri.IdentityManager");
      dojo.require("esri.arcgis.utils");
      dojo.require("dojox.mobile.Button");
      dojo.require("esri.tasks.geometry");
      dojo.require("dojox.gfx");

      var map = null;
      var gsvc = null;

      function init() {
        var urlObject = esri.urlToObject(document.location.href);
        var webmap = "59357ba9bd06409a99c0eb89f9089a40";
        var bingMapsKey ="Enter your Bing Maps Key";
        gsvc = new esri.tasks.GeometryService("http://tasks.arcgisonline.com/ArcGIS/rest/services/Geometry/GeometryServer");
        
        
        if (urlObject.query) {
          webmap = urlObject.query.webmap;
          bingMapsKey = urlObject.query.bingMapsKey;
        }

        var mapDeferred = esri.arcgis.utils.createMap(webmap, "map", {
          mapOptions: {
            slider: true
          },
          bingMapsKey: bingMapsKey,
          geometryServiceURL: "http://tasks.arcgisonline.com/ArcGIS/rest/services/Geometry/GeometryServer"
        });
        mapDeferred.addCallback(function(response) {
          map = response.map;
          dojo.connect(map, "onClick", doBuffer);
          resizeMap();

        });
        mapDeferred.addErrback(function(error) {
          console.log("Map creation failed: ", dojo.toJson(error));
        });

        
		createStoredPlaces();
      }

      function createStoredPlaces() {
    	  var surface1 = dojox.gfx.createSurface("surfaceElement1",100,100);
    	  var surface2 = dojox.gfx.createSurface("surfaceElement2",100,100);
    	  var surface3 = dojox.gfx.createSurface("surfaceElement3",100,100);

    	  surface1.createCircle({ cx: 60, cy: 60, r:30 })
  	    .setFill("green")
  	    .setStroke("pink");

    	  surface2.createCircle({ cx: 60, cy: 60, r:30 })
    	  .setFill("green")
  	    .setStroke("pink");

    	  surface3.createCircle({ cx: 60, cy: 60, r:30 })
  	    .setFill("green")
  	    .setStroke("pink");
      }

      function orientationChanged() {
                  resizeMap();
      }

      function resizeMap(){
        if(map){
           var mapCont = dojo.byId('map');
           console.log(screen.height + " height");
           mapCont.style.height = screen.height + "px";

           map.reposition();
           map.resize();
        }
      }

      function doBuffer(evt) {
          map.graphics.clear();
          var params = new esri.tasks.BufferParameters();
          params.geometries = [ evt.mapPoint ];
          alert("evt.mapPoint.x");

          //buffer in linear units such as meters, km, miles etc.
          params.distances = [ 5, 10 ];
          params.unit = esri.tasks.GeometryService.UNIT_KILOMETER;
          params.outSpatialReference = map.spatialReference;

          gsvc.buffer(params, showBuffer);
        }

        function showBuffer(geometries) {

          var symbol = new esri.symbol.SimpleFillSymbol(
            esri.symbol.SimpleFillSymbol.STYLE_SOLID,
            new esri.symbol.SimpleLineSymbol(
              esri.symbol.SimpleLineSymbol.STYLE_SOLID,
              new dojo.Color([0,0,255,0.65]), 2
            ),
            new dojo.Color([0,0,255,0.35])
          );

          dojo.forEach(geometries, function(geometry) {
            var graphic = new esri.Graphic(geometry,symbol);
            map.graphics.add(graphic);
          });
        }


      function getLocation() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(zoomToLocation, locationError);
        }
      }

      function locationError(error) {
        switch (error.code) {
        case error.PERMISSION_DENIED:
          alert("Location not provided");
          break;

        case error.POSITION_UNAVAILABLE:
          alert("Current location not available");
          break;

        case error.TIMEOUT:
          alert("Timeout");
          break;

        default:
          alert("unknown error");
          break;
        }
      }

      function zoomToLocation(location) {
        map.graphics.clear();
        var pt = esri.geometry.geographicToWebMercator(new esri.geometry.Point(location.coords.longitude, location.coords.latitude));

        var symbol = new esri.symbol.PictureMarkerSymbol('https://geoloqi.com/geoloqi-core/assets/img/logo-block.544404.png', 30, 30);
        graphic = new esri.Graphic(pt, symbol);
        map.graphics.add(graphic);

        map.centerAt(pt);
      }

      dojo.addOnLoad(init);
   </script>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Get behind this!') ?></a>
          <div class="nav-collapse">
					<ul class="nav">
<li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
               <li><a href="<?php echo $this->url('places') ?>"><?php echo $this->translate('Places') ?></a></li>
                <li class="active"><a href="<?php echo $this->url('checkin') ?>"><?php echo $this->translate('Checkin')?></a></li>
                 <li><a href="<?php echo $this->url('profile') ?>"><?php echo $this->translate('Profile')?></a></li>
					</ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <?php echo $this->content; ?>

      <hr>

      <footer>
      			<p>&copy; Doogs hacking away remotely for the Foursquare Hackathon!  <?php echo $this->translate('Go Geoloqi and Esri!') ?></p>
      </footer>

    </div> <!-- /container -->

  <?php echo $this->inlineScript() ?>
  </body>
</html>
