<div class="hero-unit" style="margin-top: 120px;">
    <h1><?php echo sprintf($this->translate('%sGlobebeta%s : focusing on place!'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('1) Sign in to Foursquare')) ?></p>
     <p><?php echo sprintf($this->translate('2) Create your place and get updates for that part of the world')) ?></p>
         <p><?php echo sprintf($this->translate('3) Check in')) ?></p> 
  <div class="row">
  <form class="form-horizontal">
    <div class="span3">
      <fieldset>
      <div class="control-group">
        <p><a class="btn btn-success btn-large" href="/user" target="_blank"><?php echo $this->translate('Connect to Foursquare') ?> &raquo;</a></p>
      </div>
      </fieldset>
    </div>
    <div class="span3">
      <fieldset>
        <div class="control-group">
            <p><a class="btn btn-success btn-large" href="/places" target="_blank"><?php echo $this->translate('Create My Place') ?> &raquo;</a></p>
        </div>
      </fieldset>
    </div>
    
        <div class="span3">
      <fieldset>
        <div class="control-group">
            <p><a class="btn btn-success btn-large" href="checkin" target="_blank"><?php echo $this->translate('Check in') ?> &raquo;</a></p>
        </div>
      </fieldset>
    </div>
  </form>
</div>
    
</div>
